version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: lumen_meilisearch_nginx
    init: true
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - lumen_meilisearch
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: lumen_meilisearch_php
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    init: true
    restart: unless-stopped
    tty: true
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    networks:
      - lumen_meilisearch
  mysql:
    image: mysql:8.0.20
    container_name: lumen_meilisearch_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumen_meilisearch
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - lumen_meilisearch
  meilisearch:
    image: getmeili/meilisearch
    container_name: lumen_meilisearch_meilisearch
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./data/meiliseach:/data.ms
    ports:
      - 7700:7700
    networks:
      - lumen_meilisearch
networks:
  lumen_meilisearch:
    driver: bridge
